# this file is autogenerated
from os import system as s
s("sass cuscu.light.scss ../../skins/cuscu.light.css --style compressed")
s("sass cuscu.dark.scss  ../../skins/cuscu.dark.css --style compressed")
            