# this file is autogenerated
from os import system as s
s("sass plainBlack.light.scss ../../skins/plainBlack.light.css --style compressed")
s("sass plainBlack.dark.scss  ../../skins/plainBlack.dark.css --style compressed")