# this file is autogenerated
from os import system as s
s("sass purple.light.scss ../../skins/purple.light.css --style compressed")
s("sass purple.dark.scss  ../../skins/purple.dark.css --style compressed")