# this file is autogenerated
from os import system as s
s("sass plainRed.light.scss ../../skins/plainRed.light.css --style compressed")
s("sass plainRed.dark.scss  ../../skins/plainRed.dark.css --style compressed")