# this file is autogenerated
from os import system as s
s("sass crissfall.light.scss ../../skins/crissfall.light.css --style compressed")
s("sass crissfall.dark.scss  ../../skins/crissfall.dark.css --style compressed")