# this file is autogenerated
from os import system as s
s("sass negros.light.scss ../../skins/negros.light.css --style compressed")
s("sass negros.dark.scss  ../../skins/negros.dark.css --style compressed")