# this file is autogenerated
from os import system as s
s("sass negro.light.scss ../../skins/negro.light.css --style compressed")
s("sass negro.dark.scss  ../../skins/negro.dark.css --style compressed")