# this file is autogenerated
from os import system as s
s("sass verde.light.scss ../../skins/verde.light.css --style compressed")
s("sass verde.dark.scss  ../../skins/verde.dark.css --style compressed")