# this file is autogenerated
from os import system as s
s("sass black.light.scss ../../skins/black.light.css --style compressed")
s("sass black.dark.scss  ../../skins/black.dark.css --style compressed")