# this file is autogenerated
from os import system as s
s("sass mario.light.scss ../../skins/mario.light.css --style compressed")
s("sass mario.dark.scss  ../../skins/mario.dark.css --style compressed")