# this file is autogenerated
from os import system as s
s("sass illarisof.light.scss ../../skins/illarisof.light.css --style compressed")
s("sass illarisof.dark.scss  ../../skins/illarisof.dark.css --style compressed")