# this file is autogenerated
from os import system as s
s("sass peru.light.scss ../../skins/peru.light.css --style compressed")
s("sass peru.dark.scss  ../../skins/peru.dark.css --style compressed")
            