# script for create an new style
# writed by Edwin Saul

from os.path import isdir, join
from os import listdir, makedirs, system

all_name_skins=[]
all_name_files=listdir("../skinsCode")

for name in all_name_files:
    if isdir(join("../skinsCode",name)):
        all_name_skins.append(name.upper())

#-----------------------------------------

def newFile(namefile,contentfile):
    f=open(namefile,"w")
    f.write(contentfile)
    f.close()
#-----------------------------------------

def createNewStyle(nameStyle):
    stylepath=str(join("../skinsCode",nameStyle))
    def filepath(name):return str(join(stylepath,name))
    makedirs(stylepath)
    #--- light theme-------
    newFile(filepath(nameStyle+".light.scss"),
f"""// theme {nameStyle}-light, for BulmaSkins by Edwin Saul  
@import "../../bulma/bulma.sass";  //import bulma            
//--------------------------------------------------------------


""")
    #--- Dark theme-------
    newFile(filepath(nameStyle+".dark.scss"),
f"""// theme {nameStyle}-dark, for BulmaSkins by Edwin Saul  
@import "{nameStyle}.light.scss";  // import {nameStyle} light skin
//--------------------------------------------------------------



""")
    #--- README.md -------
    newFile(filepath("README.md"),
f"""
# {nameStyle}            

a Theme for Bulma part of BulmaSkins             

[![ Preview {nameStyle} ](https://img.shields.io/badge/-Preview_{nameStyle}-red)](https://saul11235.github.io/BulmaSkins/view?skin={nameStyle})
[![ light mode ](https://img.shields.io/badge/-light_mode-black)](https://saul11235.github.io/BulmaSkins/view?skin={nameStyle}&dark=false)
[![ dark mode ](https://img.shields.io/badge/-dark_mode-black)](https://saul11235.github.io/BulmaSkins/view?skin={nameStyle}&dark=true)

## adding in your project
if you what to use this theme in your project put this in your html doc:

### {nameStyle}-light via CDN
```html
<link id="BulmaSkins" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Saul11235/BulmaSkins@latest/skins/{nameStyle}.light.css">
```
### {nameStyle}-dark via CDN
```html
<link id="BulmaSkins" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Saul11235/BulmaSkins@latest/skins/{nameStyle}.light.dark">
```

[![Bulma skins](https://img.shields.io/badge/-Bulma_skins-blue)](https://saul11235.github.io/BulmaSkins/)
[![By Edwin Saul](https://img.shields.io/badge/-By_Edwin_Saul-black)](https://edwinsaul.com)
            """)          
    #--- SCRIPT_render_this.py-------
    newFile(filepath("SCRIPT_render_this.py"),
f"""# this file is autogenerated
from os import system as s
s("sass {nameStyle}.light.scss ../../skins/{nameStyle}.light.css --style compressed")
s("sass {nameStyle}.dark.scss  ../../skins/{nameStyle}.dark.css --style compressed")""")
    #--- SCRIPT_render_this.py-------
    newFile(filepath("SCRIPT_create_js_for_this.py"),
f"""# this file is autogenerated
from os import system as s
s("sass {nameStyle}.light.scss ../../skins/{nameStyle}.light.css --style compressed")
s("sass {nameStyle}.dark.scss  ../../skins/{nameStyle}.dark.css --style compressed")""")
 
    #----------------------
    input (nameStyle+" created!")
    system(f"vifm ../skinsCode/{nameStyle}")
    

#------------------------------------------

newSkin=input("Name for the new style: ").replace(" ","")
if newSkin.upper() in all_name_skins:
    input("the name corresponds to an existing style")
else:
    createNewStyle(newSkin)

#-----------------------------------------

import SCRIPT_create_namestyles_js
