# this file is autogenerated
from os import system as s
s("sass plainGreen.light.scss ../../skins/plainGreen.light.css --style compressed")
s("sass plainGreen.dark.scss  ../../skins/plainGreen.dark.css --style compressed")