# this file is autogenerated
from os import system as s
s("sass plainBlue.light.scss ../../skins/plainBlue.light.css --style compressed")
s("sass plainBlue.dark.scss  ../../skins/plainBlue.dark.css --style compressed")