# this file is autogenerated
from os import system as s
s("sass perro.light.scss ../../skins/perro.light.css --style compressed")
s("sass perro.dark.scss  ../../skins/perro.dark.css --style compressed")