# this file is autogenerated
from os import system as s
s("sass plainViolet.light.scss ../../skins/plainViolet.light.css --style compressed")
s("sass plainViolet.dark.scss  ../../skins/plainViolet.dark.css --style compressed")